### ISSUE TITLE
Pagination / Load More

### ISSUE THREAD

**Issue by stolinski** [syntaxfm/website#1007]
We're currently loading the most recent 100 episodes on http://beta.syntax.fm/shows

We should either do pagination / load more / or just load all episodes at once because they are cached.

**Comment by Mostafa-Mohammadi** [comment]
A balanced approach could be to initially load a moderate number of episodes and offer a "load more" option to cater to different user preferences. This way, users can have a seamless browsing experience while maintaining reasonable performance and resource utilization.

**Comment by stolinski** [comment]
<img width="545" alt="Screenshot 2023-07-14 at 11 13 32 AM" src="https://github.com/syntaxfm/website/assets/669383/9cd6c647-ecc5-48d9-a51e-3ecfebc154a8">

Added. Initially loads 100 eps.
