### ISSUE TITLE
Investigate Queues

### ISSUE THREAD

**Issue by wesbos** [syntaxfm/website#1029]
For the transcript and AI show notes, they both take ~30-90seconds to complete. 

Not sure if we need a queue or just a cron job, but I will look into both.

https://github.com/taskforcesh/bullmq

**Comment by stolinski** [comment]
https://github.com/sindresorhus/awesome-nodejs#job-queues

**Comment by wesbos** [comment]
I think were good with just cron jobs. gonna close this
