### ISSUE TITLE
Search UI tweak suggestions

### ISSUE THREAD

**Issue by dustinknopoff** [syntaxfm/website#1060]
<img width="945" alt="Screenshot 2023-09-08 at 3 12 45 PM" src="https://github.com/syntaxfm/website/assets/23691663/2cadc059-ceba-43eb-93be-d4e8a842ec67">

Not sure if these are intentional...
* the "Search" placeholder text is a different font than the rest of the page.
* The "x" button for the modal is tiny
* Click outside modal doesn't work

**Comment by stolinski** [comment]
- [ ] Placeholder font
- [ ] X tiny
- [ ] click outside

**Comment by stolinski** [comment]
Added new clickOutsideDialog action to close native dialogs correctly onClickOutside in 1b990fe

**Comment by stolinski** [comment]
Big revamp of much of the
<img width="1100" alt="Screenshot 2023-09-14 at 2 39 26 PM" src="https://github.com/syntaxfm/website/assets/669383/cf88fe7e-54a7-460d-90fa-ed3b07c99197">
<img width="996" alt="Screenshot 2023-09-14 at 2 39 43 PM" src="https://github.com/syntaxfm/website/assets/669383/b1ecb41b-6031-419a-9fcc-f049df4c1aa5"> search ui bc760a7

<img width="1017" alt="Screenshot 2023-09-14 at 2 39 53 PM" src="https://github.com/syntaxfm/website/assets/669383/77e384c6-288d-4521-9967-80365058767c">
