### ISSUE TITLE
Heading issues

### ISSUE THREAD

**Issue by Kilian** [syntaxfm/website#1063]
There are a couple of heading issues on the site:
![Selection_1980](https://github.com/syntaxfm/website/assets/41970/1b89ff95-e4e3-40ea-8ca0-952c42c97759)

* The h1 is "by sentry", because the "syntax" SVG doesn't have a `<title>` element in it.
* Arguably that logo shouldn't be an H1
* ...because "A Tasty Treats Podcast for Web Developers" is visually the primary title. It currently is a h3, which means you skipped a level from the h1 before.
* Hosted by is a h5, which is another level skip.
* "Join our newsletter" should probably be a h3 again, because it's not a part of the list of episodes.

I would probably remove the `<H1>` from the logo (since it's not the title of the page), make the "a tasty..." the h1 and then "hosted by" either a `<H2>` or just a `<p>`

**Comment by stolinski** [comment]
Thanks for this, one of those things you hackaway on and say you'll fix later and then forget to. Making a lot of intentional changes rn.

**Comment by stolinski** [comment]
Fixes heading issues in c348ada and others. Tackling landmarks and links in next commit/

**Comment by davidengebretson** [comment]
I'd be happy to do a quick Zoom of my screen that could help you visualize what I hear with a screen reader.
Maybe we could record our session and add it as supplemental content to your podcast?
