### ISSUE TITLE
social icons have no content

### ISSUE THREAD

**Issue by Kilian** [syntaxfm/website#1064]
The social media icons for both of you are SVGs without a `<title>` so they have no text content for screen readers:

![image](https://github.com/syntaxfm/website/assets/41970/c9b0d07e-ebba-4b50-9ed5-2f8668063770)

You can add either a `<title>` to the SVG, or add an `aria-label` attribute with e.g. "Wes Bos on Twitter" as contents.

The same goes for the syntaxfm social media icons in the footer.

**Comment by stolinski** [comment]
Completed in 06ccb34

Thank you @Kilian
