### ISSUE TITLE
We need a non-visible <h1> Syntax Podcast</h1> somewhere on the home page

### ISSUE THREAD

**Issue by wesbos** [syntaxfm/website#1148]
right now the H1 is "A tasty treats...." so we should add SYntax Podcast somewhere

**Comment by davidengebretson** [comment]
Heading level 1 should always be at the beginning of the main region. The heading level 1 should also reflect the <title> element, example: a <title> of "Tasty Treat | Syntax.fm" would have a heading level 1 at the beginning of the main region that says "Tasty Treat". Heading level 1's should be designed to focus the screen reader user attention to the same place you want visually oriented folks attention to be placed when they first open the page.

Then all major sections on the paged would be at heading level 2, with subsections of the heading level2 at heading level 3. Numerically logical and semantically correct heading structure is very important so the assistive technology user will gain an equitably accessible "image" of the site layout.

I've got lots more if you want to know more. *smile*

**Comment by stolinski** [comment]
Added a visually hidden h1 and bumped down the hierarchy by 1 on the homepage. Confirmed all other pages still get the correct heading hierarchy. 68e0ed5
