### ISSUE TITLE
Missing on YT music 

### ISSUE THREAD

**Issue by longrunningprocess** [syntaxfm/website#1149]
I've been listening on Google podcasts and received an email the other day that YT Music will be the new platform for podcasts.  Syntax doesn't show up over there yet, I'm wondering if there's something you all can do about that?

**Comment by wesbos** [comment]
Interesting - Ill take a look into why

**Comment by wesbos** [comment]
seems youtube music doesnt ingest RSS feed yet, they will, but we are also going to have the podcast done in video soon so we will publish that

**Comment by longrunningprocess** [comment]
sounds good, thank you... don't want to imagine my car rides without Syntax!
