### ISSUE TITLE
Meta + title tags arent working

### ISSUE THREAD

**Issue by wesbos** [syntaxfm/website#1154]
NEed to make sure meta tags are in place

<img width="266" alt="Screenshot 2023-10-10 at 2 49 09 PM" src="https://github.com/syntaxfm/website/assets/176013/18f24968-36fb-472b-b340-66572856661f">

**Comment by stolinski** [comment]
Narrowing this down a bit more. The default meta tags aren't being loaded, because meta on something like `/shows/676/google-idx-vs-code-in-the-browser-with-david-east` is working. Will fix

**Comment by stolinski** [comment]
<Meta /> was commented out for some reason, so I just uncommented. 4dd34ac
