### ISSUE TITLE
Old URLs dont work and don't match the current site

### ISSUE THREAD

**Issue by wesbos** [syntaxfm/website#1155]
The old url strucutre doesn't seem to work? http://localhost:5173/show/676/google-idx-vs-code-in-the-browser-with-david-east

Ideally the new site would just match the old structure and use `/show/` instead of `/shows` so all old URL keep their SEO juice

Also the slugs aren't exactly the same, we should 1:1 use the same slugging library + rules for the slugs:

example the new site

http://localhost:5173/shows/650/why-is-facebook%E2%80%99s-html-css-such-a-mess

isnt the same as the old site

https://syntax.fm/show/650/why-is-facebook-s-html-css-such-a-mess

**Comment by stolinski** [comment]
Ah yeah so will merge the sluggo pr, replace with slug, then make sure importer updates slugs. On it.

**Comment by wesbos** [comment]
but we also need to make sure the slugs match the current website, which uses `speakingurl`

**Comment by stolinski** [comment]
So we should drop sluggo and slug and just use speakingurl.

**Comment by stolinski** [comment]
Updated url structure and slugs in 05ebe7b might you require you to re-run "Resync All Shows" to update slugs in your database.
