### ISSUE TITLE
On launch to prime domain, change call back for oauth to syntax.fm

### ISSUE THREAD

**Issue by stolinski** [syntaxfm/website#1163]
Authorization callback URL
is currently beta.syntax.fm, we'll need to update on promotion to main url. This issue is just a reminder.

**Comment by wesbos** [comment]
It should be flexible so it works on staging links too. Ideally just add all possible callbacks to github ?

**Comment by stolinski** [comment]
Fixed. tbh not sure you can add more than one callback here, ui only shows options for 1.
