### ISSUE TITLE
0-99 redirects should work with and without padded number

### ISSUE THREAD

**Issue by wesbos** [syntaxfm/website#1174]
https://beta.syntax.fm/1 through https://beta.syntax.fm/99 should work in addition to https://beta.syntax.fm/001

**Comment by RatulMaharaj** [comment]
Hey @wesbos 👋 

I managed to get this working by renaming `routes/(site)/[number=show_number]` to `routes/(site)/[show_number]`. 

If you're open to a PR (In the spirit of hacktoberfest 👀 ) this would be the change: https://github.com/RatulMaharaj/website/commit/f04d6280db68d96e67135b29130c9fb148aaf306

**Comment by wesbos** [comment]
thanks a ton! Please do open the PR. 

This actually hails back to a bug we had years ago. `parseInt(023) === 19`

But I dont think your PR does that because show_number will be a string, right?

**Comment by RatulMaharaj** [comment]
Oh wow, that's interesting. Deno throws a `Legacy octal literals are not available when targeting ECMAScript 5 and higher` error when you try to do this there.

I opened a PR, `show_number` will be a string so this shouldn't be a problem.

**Comment by wesbos** [comment]
Wicked - thanks a ton
