### ISSUE TITLE
Vercel WASM deployment issues

### ISSUE THREAD

**Issue by wesbos** [syntaxfm/website#1175]
I am using a `@ffmpeg.wasm/main` to concatenate the audio files before sending off for transcription.

It uses a .wasm file that when built, isn't being included in the vercel function. 

I've tried the following code:

```js
import { join } from 'path';
import { FFmpeg } from '@ffmpeg.wasm/main';
import core from '@ffmpeg.wasm/core-mt';
import wasmPathAb from '@ffmpeg.wasm/core-mt/dist/core.wasm?url';

const wasmPath = join(process.cwd(), wasmPathAb);
const ffmpeg = await FFmpeg.create({
	core: core,
	coreOptions: {
		wasmPath: wasmPath
	},
});
```

And that successfully includes the file in the vercel output. but this error persists:

```
RuntimeError: Aborted(Error: ENOENT: no such file or directory, open '/var/task/_app/immutable/assets/core.5838ff71.wasm'). Build with -sASSERTIONS for more info.
```

The file is confirmed at that path (in the vercel output), but the function is unable to access it at runtime. 

Not sure how to force it to include that file in the function. Any ideas?

Related:

https://github.com/sveltejs/kit/issues/10594
https://github.com/sveltejs/kit/pull/8441

**Comment by wesbos** [comment]
Still struggling with this one. It seems vercel needs the assets to be statically analyzable. But even with this code:

```js
const wasmPath = _dirname + '/../assets/core.wasm';
```

**Comment by wesbos** [comment]
As an update, this seemesly has nothing to do with ESM/CJS or even the fact that it's a wasm file as I can't even get it to work with an SVG and [the instructions here](https://vercel.com/guides/how-can-i-use-files-in-serverless-functions). **I just need to know how do I get vercel to include a file in the built function?**

**Comment by sandrinjoy** [comment]
serverless runs in random cloud machines, 
so, why not try storing the file in public folder, and access it using absolute path url?

**Comment by wesbos** [comment]
I tried that - same issue - vercel doesn't know to bundle it with the function. If I understand the issue, putting it in the public / assets folder makes it a vercel CDN asset, and its not available in the function environment.

**Comment by wesbos** [comment]
I have the file being moved into the function now manually post-build. Kind of silly because it copies a 23mb wasm file into EVERY serverless function, but that seems to now make it available.

Thanks to:

https://twitter.com/dimfeld/status/1714684628802699436

code: https://github.com/dimfeld/website/blob/master/copy_content_to_build_destination.mjs

**Comment by dimfeld** [comment]
With a bit of extra work you can figure out the exact function you need, by looking at `.vercel/output/config.json`. Here's an excerpt of config.json from building my website repo above, and you can see the mapping from the `src` route to the `dest` function that ends up handling the route.

```jsonc
{
  "version": 3,
  "routes": [
                // Removed a bunch of other routes for brevity.
		{
			"src": "^/notes/([^/]+?)\\.og-image\\.png/?(?:/__data.json)?$",
			"dest": "/fn-0"
		},
		{
			"src": "^/plas/event/?(?:/__data.json)?$",
			"dest": "/fn-1"
		},
		{
			"src": "^/plas/script\\.js/?(?:/__data.json)?$",
			"dest": "/fn-1"
		},
		{
			"src": "^/repl/([^/]+?)\\.json/?(?:/__data.json)?$",
			"dest": "/fn-0"
		},
		{
			"src": "^/writing/([^/]+?)\\.og-image\\.png/?(?:/__data.json)?$",
			"dest": "/fn-0"
		}
  ]
}
```

**Comment by wesbos** [comment]
Thanks again @dimfeld - your fix was the ticket!
