### ISSUE TITLE
Player needs a way to be opened after it's been closed

### ISSUE THREAD

**Issue by wesbos** [syntaxfm/website#1195]
right now if you close the player, it keeps playing, but there isn't a way to get it back open unless you click play on the audio again.

Would be nice for it to minimize into just the show title / 1 line high

**Comment by RatulMaharaj** [comment]
Can we get a hotkey? 👀

**Comment by wesbos** [comment]
Ooo yah, what should the key be?

**Comment by davidengebretson** [comment]
'p' for us screen reader users jumps to the next paragraph and reads it. Single key hotkeys are mostly taken up by screen reader manufacturers. Kind of a bummer and a pain, I know.



I can "pass a key through to the application/browser, but that can provide UX issues for those of us who need to use assistive technologies to equitably access browser functionality.



Best,

David

**Comment by wesbos** [comment]
I think this issue needs to be in three parts:

1) We need to stop the audio when users click the x
2) We need a way to minimize the player / make a slim player
3) we need keyboard shortcuts

**Comment by RatulMaharaj** [comment]
I'm really keen to help out with this 🙋🏽‍♂️

I converted my hotkey PR to a draft for now - I think I could maybe tackle part 1 & 3 perhaps with some guidance on what you would want the shortcuts to be/do.

Also, perhaps a part 4 would be having some UI that shows you what shortcuts are available?

**Comment by wesbos** [comment]
Awesome, yes would love the help! 

Some guidance: 

1. you'll have to expand the close() function in `player.ts`. probably do two things:

state.audio?.pause(); // pause it
state.current_show = null; // remove current show

2. youll need to make a new $player.status state called "MINIMIZED", which corresponds to a slim UI of the player. Maybe just the scrubber bar and an icon to maximize it again?

3. you did it

4. Site wide `?` keyboard shortcut that opens up a popover (see Popover API stuff scott did) to display all the possible shortcuts. Ideally this is generated from a list of the shortcuts available and not just HTML

**Comment by stolinski** [comment]
This has been fixed with a minimized player and closing player resetting the player.
