### ISSUE TITLE
URLs must be /show/##/slug

### ISSUE THREAD

**Issue by wesbos** [syntaxfm/website#1198]
Current site is `/show/SHOW_NUMBER/SLUG`

new site is `/shows/SHOW_NUMBER/SLUG`with a 302 redirect for any old the old style URLs

I really think we should persist the old structure and not mess with redirects, for the sake of all the google juice we have gained over the years

**Comment by wesbos** [comment]
fixed

**Comment by stolinski** [comment]
Reopening because this change broke `localhost:5173/671` routes redirect.

**Comment by stolinski** [comment]
K fixed in f3417a5
