### ISSUE TITLE
Dropdown colors are off on darkmode

### ISSUE THREAD

**Issue by wesbos** [syntaxfm/website#1202]
<img width="472" alt="Screenshot 2023-10-19 at 3 50 15 PM" src="https://github.com/syntaxfm/website/assets/176013/e81a57eb-f870-4bf7-a22c-a57627c55557">

**Comment by stolinski** [comment]
<img width="402" alt="Screenshot 2023-10-20 at 9 01 57 AM" src="https://github.com/syntaxfm/website/assets/669383/65416e92-3771-4f14-9c7f-bedd2a2e595c">
<img width="365" alt="Screenshot 2023-10-20 at 9 23 38 AM" src="https://github.com/syntaxfm/website/assets/669383/bbbd0bee-81e4-4e11-a4bf-a5f7db355eb6">

Fixed.
