### ISSUE TITLE
Bring the Sick Picks page back

### ISSUE THREAD

**Issue by wesbos** [syntaxfm/website#1210]
someone wrote a regex matcher for the sick picks out of the show notes. I'm wondering if we can do something similar but even better...

**Comment by wesbos** [comment]
Yep - that is the commit. 

We would need to loop over and parse the sick picks fro every single show note. It would be pretty usage intensive, so we could cache them in redis for ~1 week.  I can help with that part if want to take a stab at creating a /sickpicks page.

**Comment by wesbos** [comment]
hmm seems like that implementation was for the result HTML, we only have MD in the database. Ill see if I can find a good way to do it

**Comment by wesbos** [comment]
ITS LIVE https://syntax.fm/sickpicks

**Comment by themisterholliday** [comment]
@wesbos Nice! You're too quick!
