### ISSUE TITLE
Broken Show Accordion Link 

### ISSUE THREAD

**Issue by jaypostle** [syntaxfm/website#1214]
Context: the Show/Transcript accordion tabs
Error at: when clicking Transcript tab (no issue) and clicking back to Show.
Best guess: looks like it's an incorrect link in "Show"
should be /show not /shows
https://syntax.fm/show/682/design-systems-with-brad-frost/transcript

<img width="268" alt="Screenshot 2023-10-20 at 9 13 47 AM" src="https://github.com/syntaxfm/website/assets/50502972/7348d2c9-0da0-4713-b648-e0fe2923f568">

**Comment by stolinski** [comment]
Closed here: https://github.com/syntaxfm/website/pull/1216
