### ISSUE TITLE
Potluck questions form

### ISSUE THREAD

**Issue by cpenned** [syntaxfm/website#1217]
I notice you’re using a Google Form here: https://syntax.fm/potluck

If you’re just wanting to capture the data in a Google Sheet, you can actually set up a quick little post request using gscript (https://developers.google.com/apps-script/guides/web). That way you can have a styled form and still capture the data in a Google sheet.

Looking quickly, you'd need to: 
1. Create an app script for the sheet
Extensions > Apps Scripts (in the google sheet)

2. Add a doPost function to the script
Testing quickly, it looks like this would work (like this is literally all the code you need)

function doPost(e) {
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("Sheet1") // or whatever the name of your sheet is
  const params = e.parameter;
  sheet.appendRow([params.name,params.question])
  return ContentService.createTextOutput("{message: success}")
}

3. Deploy the web app.
- Click Deploy. 
- Select web app type. 
- Change “Who has access” to anyone
- Deploy and authorize your app.

4. Hook up the form to the endpoint
Just do a POST to the endpoint and pass the formData to the body. Assuming you have just two fields like your current form: name and question), the script should just work. 

Using the Google Sheet may be temporary and you may have plans to store these questions somewhere else, but figured I'd ping you in case it can be a help.

**Comment by wesbos** [comment]
that is pretty sweet - I think we want to even take it 1 step further and have people submit the questions into our DB, that way our workflow for doing the show will be even easier.

**Comment by cpenned** [comment]
Ah, okay. Figured the google form was a stop gap, but figured I'd mention it just in case :)
