### ISSUE TITLE
click on search result showing 404 error

### ISSUE THREAD

**Issue by ryandungle** [syntaxfm/website#1219]
when I search and click on one of the result it will go to a link like this https://syntax.fm/**shows**/448/potluck-multi-tenant-apps-js-sprinkles-kids-coding-server-error-handling

I need to change shows => show to make the page display. https://syntax.fm/**show**/448/potluck-multi-tenant-apps-js-sprinkles-kids-coding-server-error-handling

**Comment by stolinski** [comment]
Ah another victim of the /shows/ show/ switch on it.

**Comment by stolinski** [comment]
Didn't mean to close, but a fix is going up now.
