### ISSUE TITLE
Invalid fallback avatar on home page

### ISSUE THREAD

**Issue by RatulMaharaj** [syntaxfm/website#1223]
#### Bug

The fallback github account being passed into the `FacePile` component for guests is invalid.

Currently the fallback github account is `''` which results in the avatar url being set to `https://github.com/.png`. 

I believe the fallback should be `null` similar to what is being done on the individual show page (in the `HostsAndGuests` component) which will result in the fallback avatar being `https://github.com/null.png`

#### Screenshots

<img width="364" alt="image" src="https://github.com/syntaxfm/website/assets/56479869/990ff6b8-d105-4bbe-b25b-66f9a661f768">

**Comment by wesbos** [comment]
thank you!
