### ISSUE TITLE
Edit Show Notes button has duplicate `/shows` in the URL leading to 404.

### ISSUE THREAD

**Issue by r3Fuze** [syntaxfm/website#1224]
There are one too many `/shows` in the URL for the `Edit Show Notes` button, which means you get a "file not found" on GitHub.

Example: [`https://github.com/syntaxfm/website/tree/main/shows/shows/681%20-%20AI.md`](https://github.com/syntaxfm/website/tree/main/shows/shows/681%20-%20AI.md)

Removing one of the `/shows` leads to the correct GitHub page.

**Comment by wesbos** [comment]
thank you! fixed https://github.com/syntaxfm/website/pull/1230
