### ISSUE TITLE
Suggestion: episode number overlapping the episode number

### ISSUE THREAD

**Issue by BradDuns** [syntaxfm/website#1237]
On the main page, in the episode grid, the first line gives details like "Supper Club x 3 Days Ago x 682." When that line is a little longer it blocks the yellow episode number. The text overlapping looks good on your `/shows` page when it's the episode title, but looks a little weird when the episode number is blocking the same number.

![image](https://github.com/syntaxfm/website/assets/3791599/b99a4866-5c46-4864-88ac-cfbd0435a33e)

**Comment by wesbos** [comment]
you are right - I didn't account for this. Ill fix it up!

**Comment by wesbos** [comment]
we dont really need the show number in there. I added it last week but I dont see why..

**Comment by wesbos** [comment]
fixed https://github.com/syntaxfm/website/pull/1238
