### ISSUE TITLE
Scott update your github avatar

### ISSUE THREAD

**Issue by wesbos** [syntaxfm/website#1242]
https://twitter.com/PeteCapeCod/status/1716502088560112039

the greyscale looks bad on the website @stolinski

**Comment by stolinski** [comment]
<img width="554" alt="Screenshot 2023-10-27 at 10 19 28 AM" src="https://github.com/syntaxfm/website/assets/669383/f504e565-8396-4828-af3e-6b04e9a3cb71">

Updated, now cache needs to recache

**Comment by stolinski** [comment]
<img width="1407" alt="Screenshot 2023-10-27 at 10 21 30 AM" src="https://github.com/syntaxfm/website/assets/669383/7db07d97-3b5e-4598-ac2f-d26d3ab8f565">

Confirmed.
