### ISSUE TITLE
Team member photos get inverted on hover when going back on hover

### ISSUE THREAD

**Issue by manuelsavino** [syntaxfm/website#1243]
Not sure if this is by design, however when on https://syntax.fm/about, if you go back while you're hovering any of the team member's photos and come back to /about, the images get inverted where the younger version shows by default and more recent photo to the team member shows on hover. 

https://github.com/syntaxfm/website/assets/1297799/a927e331-e009-48b4-99ab-8134242fae74

**Comment by wesbos** [comment]
Can't replicate this, but I think we will leave this as a feature :) Time traveling on the website shows you time travel photos? thanks for the issue
