### ISSUE TITLE
Pagination pages are not updated

### ISSUE THREAD

**Issue by richardberube** [syntaxfm/website#1245]
When you go to a page that will not exist when you change the number of shows per pages, the number of pages do not refresh.

Example: 
1. Select the last page (currently 69) while on the "10 per page"
2. Select "40 per page"
3. You are still left on page 69, so all page 19 to 69 are empty.
4. Only way to fix is refreshing the page

**Comment by wesbos** [comment]
thanks - working on this now!

**Comment by wesbos** [comment]
fixed! Thanks a ton
