### ISSUE TITLE
Close button doesn't work on theme picker

### ISSUE THREAD

**Issue by peanutbutterjlly** [syntaxfm/website#1247]
When you go to the page: https://syntax.fm/system/theme a theme picker shows up on the right side with a close/x button but that button doesn't work. 

when you click out the menu, it scrolls away. 

on a late 2014 Mac, Big Sur 11.7.10, Chrome 118

**Comment by wesbos** [comment]
I get this too, I was using ⌘ E to open + close. I think its related to the clickoutside of the popover

**Comment by wesbos** [comment]
This emoji is in the way! <img width="315" alt="Screenshot 2023-10-23 at 3 05 32 PM" src="https://github.com/syntaxfm/website/assets/176013/07e288e2-280e-49ef-90a3-d78995abc33a">

**Comment by wesbos** [comment]
fixed !
