### ISSUE TITLE
Guest avatar is missing from the show card on the guest page

### ISSUE THREAD

**Issue by MarcL** [syntaxfm/website#1260]
Loving the new site!

I'm not sure if this is intentional but the guest avatar is missing from the show cards which appear on the guest page.
I thought I'd let you know.

## Example

In the episode with David East, his avatar is missing:

URL: https://syntax.fm/guest/david-east

![CleanShot 2023-10-23 at 21 48 33@2x](https://github.com/syntaxfm/website/assets/1965510/bae43a16-a10f-4faf-a558-4b6edabc2852)

I wasn't sure from the query below whether it retrieves the guest or not:

https://github.com/syntaxfm/website/blob/main/src/routes/(site)/guest/%5Bname_slug%5D/%2Bpage.server.ts

However, from the schema it looks like a show should have all of the guests in it.
https://github.com/syntaxfm/website/blob/main/prisma/schema.prisma#L117C18-L117C18

Happy to PR if you point me in the right direction but it also might be intentional so didn't want to assume.

Thanks,
Marc

**Comment by wesbos** [comment]
Waiting for #1302 before tackling

**Comment by wesbos** [comment]
fixed!

**Comment by MarcL** [comment]
Nice! Thanks, Wes! 🎉
