### ISSUE TITLE
iOS Lockscreen: Missing metadata

### ISSUE THREAD

**Issue by RatulMaharaj** [syntaxfm/website#1264]
#### Issue

When an episode is playing on iOS (and potentially other platforms), the meta data typically available to a listener i.e. `title`, `artist` and `artwork` is missing.

#### Potential Solution
I think this can be added using: 
```ts
navigator.mediaSession.metadata = new MediaMetadata({ ... });
```

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/mediaSession

#### Screenshots

![Group 45](https://github.com/syntaxfm/website/assets/56479869/3f626fb9-50e0-414f-a8c7-de7bec7ad2a9)

**Comment by wesbos** [comment]
I was JUST wondering how to do this. I thought it might be taken from the MP3, but apparently not. Will investigate

**Comment by wesbos** [comment]
Looks like the first search result also uses Syntax as an example! https://dbushell.com/2023/03/20/ios-pwa-media-session-api/

**Comment by wesbos** [comment]
Mac Desktop

<img width="181" alt="Screenshot 2023-10-24 at 8 52 12 PM" src="https://github.com/syntaxfm/website/assets/176013/3fd67838-57f6-4bfa-8e30-816b7b25dc18">

Mobile ios needs 128x128 but looks like the above

**Comment by wesbos** [comment]
implemented!
