### ISSUE TITLE
Guest Metadata isn't updating when changes

### ISSUE THREAD

**Issue by wesbos** [syntaxfm/website#1302]
we just added all the guest meta to past shows, but when running an import it doesn't update the guest data.

**Comment by stolinski** [comment]
I have it fixed on dev, but guest data doesn't seem to be updating on live yet. Will have to dive in more once I get these TikToks done.

**Comment by stolinski** [comment]
Syncing fixed with prisma fix. https://syntax.fm/show/682/design-systems-with-brad-frost
