### ISSUE TITLE
Images overlay text-color in about section

### ISSUE THREAD

**Issue by pranavgoel29** [syntaxfm/website#1319]
Link to the section - https://syntax.fm/about

I noticed the text color is changing for Ben, from white to black on hover.
However, it is the same for everyone else card. Is it intended behavior or a bug?

Hover on Ben's card - 
![image](https://github.com/syntaxfm/website/assets/48860494/e2a635db-dcd5-4a2e-8b54-16cd6833aa4c)

Hover on Wes's card - 
![image](https://github.com/syntaxfm/website/assets/48860494/19766167-0486-4b12-afd2-41755510b49b)

**Comment by wesbos** [comment]
THe black is intentional so its readable on bens hover. BUt you found a bug in that the card doesnt swap photos if you hover on the persons name

**Comment by wesbos** [comment]
fixed

**Comment by pranavgoel29** [comment]
Loving the cursor change on hover, hehe 😁
