### ISSUE TITLE
Total episodes numbers mismatch in the about section.

### ISSUE THREAD

**Issue by pranavgoel29** [syntaxfm/website#1348]
Not sure if this is a bug.
I have noticed that in about section the no. of episodes mentioned doesn't match the total number by `1`.
![image](https://github.com/syntaxfm/website/assets/48860494/0d3b5958-44d7-42d1-934f-aa082a178b77)

The Shows page
![image](https://github.com/syntaxfm/website/assets/48860494/6d805bf1-fe8a-4a7d-bb98-643f9a583fbc)

### The episodes start from the number '0' which makes the total number of episodes `688` and not '689'.

Am I missing something? 🤔

**Comment by wesbos** [comment]
This might be related to it counting future episodes - we need to adjust that query to only count episodes that are published
