### ISSUE TITLE
Question: What is the best way to follow up with the Syntax crew on topics covered?

### ISSUE THREAD

**Issue by outwebbed** [syntaxfm/website#1349]
Recently I listened to a Syntax episode where questions from the Potluck form were covered. Personally I had some insights to share regarding one of the topics covered and so my question is...should I simply use the Potluck form to provide my long-form thoughts on topics covered from a previous Potluck content review episode? Or should I supply here in the website repo issues?

Simply want to reach out with feedback on show content but in a way that is helpful / encouraged. Thank you!

**Comment by benvinegar** [comment]
Hey @outwebbed – Potluck is one, or you could join [our Discord](https://discord.com/invite/NKqtxMh) which isn't well publicized (and admittedly, we're only occasionally active).
