### ISSUE TITLE
Pagination miscount

### ISSUE THREAD

**Issue by mbrambilla** [syntaxfm/website#1352]
Pagination can be slightly off in the page count, showing more pages that what the number of episodes should result in.  Note, in this case, going to click on page 70 or the `->->` (Last page) button results in being pushed to page 1.

This is occurring with the current count of 688 episodes.

![Screenshot 2023-11-03 101628](https://github.com/syntaxfm/website/assets/4764134/87834f9a-9d40-46e1-8202-8797d98735f7)

This is using the default pagination settings:

![Screenshot 2023-11-03 102307](https://github.com/syntaxfm/website/assets/4764134/f53667ab-0b41-42c9-8448-c0c4b180bf8c)

**Comment by stolinski** [comment]
Same type of issue as https://github.com/syntaxfm/website/issues/1348 
shows.count is counting the unreleased shows.
