### ISSUE TITLE
Width issue on mobile

### ISSUE THREAD

**Issue by rmso27** [syntaxfm/website#1357]
Hi,

In some episodes, the width of the episode page is exceeding the iPhone screen and forces you to scroll vertically to see all content. This only happens in some episodes.

![IMG_6834](https://github.com/syntaxfm/website/assets/32513680/56cc7e24-aaaa-4626-aca1-5268221e41ac)

I’m using an iPhone 12.

regards,

**Comment by stolinski** [comment]
I'm guessing there is something like the tags pushing this wide since it's not happening on all pages.
