### ISSUE TITLE
Improve Cards Layout

### ISSUE THREAD

**Issue by aidev13** [syntaxfm/website#1359]
I found your old site quite a bit easier to navigate show episodes. The new site I find the bigger cards for the shows on mobile be kinda annoying and I have actually found myself being less interested to listen because of the difficulty browsing the site. My humble suggestion would be to make the show cards like 50% or more smaller for easier mobile experience.

**Comment by wesbos** [comment]
Good feedback. Another question - do you wish you could see more recent episodes at a time without using the pagination?

**Comment by aidev13** [comment]
Yes, I think pagination in this case is good for desktop UI, but in most mobile the less button touching = a better UX. :)

**Comment by stolinski** [comment]
We had a much tighter "list" view for the cards, I wonder if that can come back via a toggle.

**Comment by aidev13** [comment]
That would be nice! I have been finding myself not searching for new shows to listening to as much and even have lost interest due to the current new layout. It's crazy how a UI/UX can do that! And I Love syntax so much so I bought a shirt!

**Comment by wesbos** [comment]
@aidev13 are you using the shows page, or the home page? I'm wondering if we need to re-think the cards on both.

**Comment by wesbos** [comment]
Thanks - I agree, I did like the huge list much better. 

Can tackle this at the same time: https://github.com/syntaxfm/website/issues/1432

**Comment by wesbos** [comment]
the cards layout has been improved - let us know what you think!
