### ISSUE TITLE
Reinstate Episode saving 

### ISSUE THREAD

**Issue by wesbos** [syntaxfm/website#1363]
A few complaints that we dont have the current time of the podcast saved, which is annoying if you reload a page or want to come back to an episode.

So, on `timeupdate` of the audio, we just need to mirror the player currentTime to localStorage with a key for the show.

Then when someone plays a show, check and see if we have that show progress in localStorage, if so, jump to that timestamp.

> I know this is new website. I listen on phone, phone is only source of truth for me. Phone experience is worse. It used to save my session and does no longer. I'm in car listening to podcast, I go grocery shopping and switch to headphones. It keeps getting out of sync or resetting. Obviously I keep listening and deal with this because you guys are the best, but would be great to fix this

**Comment by wesbos** [comment]
This is a good one if any listeners want to take it on

**Comment by wesbos** [comment]
related: https://github.com/syntaxfm/website/issues/1369

**Comment by pranavgoel29** [comment]
> Paging @stolinski   - hes working on making it easier to run locally right now! 

Awesome 😁

**Comment by pranavgoel29** [comment]
Hey, just curious if there's any updates on this?

**Comment by stolinski** [comment]
Working on some updates for this stuff today including saving to browser cache for offline / spotty network play. Not sure if I'll complete today but this kind of syncing would be great to put into my branch.
