### ISSUE TITLE
[a11y]: Homepage - Episode cards read entire content to screen readers

### ISSUE THREAD

**Issue by freaksauce** [syntaxfm/website#1383]
Due to the shows being a link with the entire content inside, screen readers such as VoiceOver read the entire article contents as the link text which leads to an unnecessary increase in cognitive load for users. This information could be condensed and included as an `aria-label` on the `<a>` to make it easier for users to navigate. If you also hook up the `aria-describedby` attribute it will give screen reader users an option to also listen to that text too, you will need to add a unique id to the `<p class="description">` however.

eg,
```
<article class="card">
  
  <a
    href=""
    aria-label="Episode 693 posted 4 days ago, Tasty, Lessons Learned & Bugs Fixed from Launching Syntax.fm"
    aria-describedby="show693-description"
  >
    ...
    <p class="description text-sm svelte-1qdj79" id="show693-description">Scott and Wes discuss launching the new Syntax.fm site, including database timeouts from too much data, the importance of error monitoring, dark mode UI bugs, using AI for show notes, managing background jobs with serverless, launching with TypeScript errors, having fast local development, being mindful of payload sizes, taking advantage of new browser APIs, and how Wes helped improve the overall design.</p>
  </a>
</article>
```

**Comment by wesbos** [comment]
Hey @freaksauce thanks a ton for the clear suggestion - such an easy fix. Implemented it here: https://github.com/syntaxfm/website/pull/1415
