### ISSUE TITLE
Audio controls - add padding to right of volume slider

### ISSUE THREAD

**Issue by michaelongaro** [syntaxfm/website#1385]
It's a small change but I think matching the padding on the left side of the controls looks nice.

Before:
![before](https://github.com/syntaxfm/website/assets/35980684/85775989-2db7-4239-bc2c-52d8651e33aa)

After:
![after](https://github.com/syntaxfm/website/assets/35980684/ec549e08-0f45-45b6-85bf-8a37fdc9771b)

**Comment by wesbos** [comment]
Hmm, i dont see the "before". Which browser is this?

**Comment by wesbos** [comment]
Tried it in a few browsers, please re-open if it's still an issue :)
