### ISSUE TITLE
Select not working correctly on episodes per page

### ISSUE THREAD

**Issue by polettoweb** [syntaxfm/website#1391]
In the page listing all the episodes, if you modify the number of episodes seen, there is a problem with the select input.

When clicking on the desired value, the value is set correctly, and the page will show the new value of episodes, but the select will not close and remain open until you click on it or outside.

<img width="610" alt="Screenshot 2023-11-22 at 21 24 21" src="https://github.com/syntaxfm/website/assets/13413857/e794cb90-245a-436f-8a34-297c17a41097">

**Comment by kjroelke** [comment]
Also happens on mobile and web app version (aka I used iOS "Add to Home Screen"). 

Same bug, but slightly different appearance ![image](https://github.com/syntaxfm/website/assets/16909402/ef2c55c6-8c63-45ba-a087-87c690e03e85)

**Comment by wesbos** [comment]
Seems like we need ot call hidePopover() when a value is selected.. Researching..

**Comment by wesbos** [comment]
fixed it: https://github.com/syntaxfm/website/pull/1413
