### ISSUE TITLE
[Windows + Chrome] Fix for audio controls padding

### ISSUE THREAD

**Issue by michaelongaro** [syntaxfm/website#1414]
I didn't see an option to reopen my previous issue so this is basically the same as #1385.

OS: Windows 11 Home (10.0.23590)
Browser: Chrome (119.0.6045.200)

Firefox rendered as expected in regards to the right padding.
I don't have a mac but it rendered properly on BrowserStack's view of Chrome 119 on macOS Sonoma.

Screenshot of what I currently see where the container doesn't respect the size of the scrollbar:
![originalChrome](https://github.com/syntaxfm/website/assets/35980684/2bd042dc-0472-42ca-84a6-3a284467897a)

I am not sure if this has consequences in other browsers, but setting ```width: 100%;``` to the ```<section>``` wrapping container seems to fix it! After doing this it looks like it should:

![fixedChrome](https://github.com/syntaxfm/website/assets/35980684/bef05604-2059-4ccb-8743-2f60f6eb00cb)

**Comment by wesbos** [comment]
it's width: 100vw! your fix of width:100% fixes it. Makes sense, 100vw includes the scrollbar. 100% doesn't

**Comment by wesbos** [comment]
thanks again @michaelongaro - great detective work

**Comment by michaelongaro** [comment]
Of course! Thanks for the quick feedback :) Looks great on my end now
