### ISSUE TITLE
[Bug] [A11y] Contrast on Episode Cards in most themes

### ISSUE THREAD

**Issue by therealphatmike** [syntaxfm/website#1432]
The description text for an episode is very difficult to read in all themes except light mode. In certain modes (dark and Sentry) the title can also be difficult to read.

There should either be a backing behind the text or the card should be formatted such that the text will always render below the episode number.

<img width="1214" alt="Screenshot 2023-12-06 at 10 53 49" src="https://github.com/syntaxfm/website/assets/12776258/83073137-a9dd-4cbf-8b2a-0f3316a9ce93">
<img width="1222" alt="Screenshot 2023-12-06 at 10 55 17" src="https://github.com/syntaxfm/website/assets/12776258/14968521-3300-462b-a1bc-bdacca5acd51">
<img width="1197" alt="Screenshot 2023-12-06 at 10 55 34" src="https://github.com/syntaxfm/website/assets/12776258/6be546ac-91ae-4b3e-9623-6817abb7f1cd">

**Comment by wesbos** [comment]
Thanks a ton. there was a background color the text, but it seems to not be applied in light mode. 

<img width="832" alt="Screenshot 2023-12-06 at 4 19 32 PM" src="https://github.com/syntaxfm/website/assets/176013/97b18bbb-6478-40c0-a3f0-309fa11bdc10">

**Comment by garyb1** [comment]
Hey @wesbos  @therealphatmike  any thoughts on utilising the `ch` unit here for the line length of the description in the card? Baymard did research around the [optimal line length](https://baymard.com/blog/line-length-readability). Andy bell employs the ch unit in a similar way on his [set.studio blog cards](https://set.studio/blog/), only with a max `50ch` width.

Before: Spanning full width of the card.

<img width="1017" alt="Syntax.fm show card with a description spanning the full width of the card" src="https://github.com/syntaxfm/website/assets/12486130/52c9282c-81ac-4c81-927c-eca0d0328ed8">


After: This example uses `max-width: 65ch`.

<img width="991" alt="Syntax.fm show card with a max-width assigned to the description" src="https://github.com/syntaxfm/website/assets/12486130/d561d6d9-8da4-433c-ac7b-8a7ff0d0f0d6">

**Comment by therealphatmike** [comment]
@garyb1 It's not a bad suggestion, it just may go against the intended design ethos. The interplay of the text and the large episode number in the background may be an intentional aesthetic that they don't want to lose--I personally feel the site loses a bit of it's "grunge" factor by making the separations too neat.

It's worth noting that this has implication on both the episode title and the description text.

Here's an example of an episode where the title flows onto the episode number as well.
<img width="1223" alt="Screenshot 2023-12-12 at 10 06 45" src="https://github.com/syntaxfm/website/assets/12776258/9927357f-a3ef-4619-9859-2a4e762063bd">

With a background color on the text, we get something akin to
<img width="1201" alt="Screenshot 2023-12-12 at 10 20 09" src="https://github.com/syntaxfm/website/assets/12776258/76e00236-9a33-4e6d-8bb0-443203a3776b">

With the max-width we get
<img width="1238" alt="Screenshot 2023-12-12 at 10 11 14" src="https://github.com/syntaxfm/website/assets/12776258/8d5f33e9-79be-410f-a76a-0b733780879f">

In my opinion, the max-width doesn't feel like it's a component for the same site. Obviously, Scott and Wes have the last word on that, but I figured I'd throw in my two cents.

As far as providing a bg color on the description text, again I've come to the same conclusion
<img width="1223" alt="Screenshot 2023-12-12 at 10 20 20" src="https://github.com/syntaxfm/website/assets/12776258/78d380c8-4f76-4811-9daf-86932f14164e">

bg color applied:
<img width="1199" alt="Screenshot 2023-12-12 at 10 20 46" src="https://github.com/syntaxfm/website/assets/12776258/1e799169-cd1b-4422-ab5a-4b41327efa5c">

max width applied;
<img width="1213" alt="Screenshot 2023-12-12 at 10 25 00" src="https://github.com/syntaxfm/website/assets/12776258/8959d9d1-934c-463b-a4f2-9e25278aada4">


Again, I feel it just loses...something.
