### ISSUE TITLE
Episode Pages: Add Next/Previous Episode buttons to navigate forwards/backwards

### ISSUE THREAD

**Issue by devjusty** [syntaxfm/website#1446]
Hi guys,

Loving the new site but it looks like individual episode pages are missing an easy way to navigate forward and backward to adjacent episodes without going back to the shows page.

**Comment by themisterholliday** [comment]
We could add a next and previous button to the show page. The issue would be having an easy/consistent way to navigate to the previous and following shows.

We can't redirect to `{show.number - 1}` as far as I can see, we need the show slug.
So, I'm not sure how we would do this without requesting the episode before and after the current episode when loading the page.

@stolinski @wesbos Any thoughts on this?

**Comment by stolinski** [comment]
This is a good idea and i'd like to do it. But want to think through the UI a bit.

**Comment by stolinski** [comment]
This actually would be as easy as show.number -/+ 1 since we have the /number routes. Should be easy enough to add.

**Comment by themisterholliday** [comment]
Right now it looks like we have two show routes 
`show/[show_number]/[slug]` and `show/[...all]`

Which seems to mean `https://syntax.fm/show/746/infrastructure-for-ts-devs-kubernetes-wasm-and-containers-with-david-flanagan` is valid but `https://syntax.fm/show/746` will redirect to `/shows`.

That is what my previous comment was referring to.

Though with how this is setup `https://syntax.fm/show/745/infrastructure-for-ts-devs-kubernetes-wasm-and-containers-with-david-flanagan` works, the slug would just be incorrect.

**Comment by wesbos** [comment]
You can use the short urls and they redirect? Or would that kill the SPA Part of the app and stop audio? We might need to query the prev and next with the current show, but just the slug

**Comment by themisterholliday** [comment]
> You can use the short urls and they redirect? Or would that kill the SPA Part of the app and stop audio? We might need to query the prev and next with the current show, but just the slug

The short urls redirect to the `/shows` page. The audio continues regardless. I would be in favor of querying the prev and next shows if it seems okay for this scenario.


I opened [a PR](https://github.com/syntaxfm/website/pull/1614) to try and show what I'm seeing.

```<a href={`/show/${show.number - 1}/${show.slug}`}> PREVIOUS </a>```
This is the line that will have the wrong slug in the Episode Page because there has to be a slug or we will redirect to the `/shows` page.

**Comment by wesbos** [comment]
Sorry I mean the /### url.  

Syntax.fm/600 

I don't think this will work because it's a redirect page and I think linking to the full URL will be better for SEO

**Comment by themisterholliday** [comment]
Ah okay this is my mistake. I keep trying to do `/show/###` rather than just `/###`.
I think that is where the misunderstanding is.

**Comment by wesbos** [comment]
eh?

![image](https://github.com/syntaxfm/website/assets/176013/0a4945d6-d09a-472c-8cd0-9f1a5591a02f)
