### ISSUE TITLE
Use social badges to get closer to front-end engineers

### ISSUE THREAD

**Issue by LitoMore** [syntaxfm/website#1460]
I've notice we have some social links at the homepage:

![CleanShot 2023-12-16 at 16 58 47@2x](https://github.com/syntaxfm/website/assets/8186898/f29a31e6-4e94-4e1f-b9a7-1b0b772094dc)

How about using the most popular badge service for social links? I've listed three styles for preview:

(I've corrected the `PocketCasts` to `Pocket Casts` to follow their official spell. See https://pocketcasts.com.)

### Flat style

![RSS](https://img.shields.io/badge/RSS-ffa500?logo=rss&logoColor=fff)
![Spotify](https://img.shields.io/badge/Spotify-1db954?logo=spotify&logoColor=fff)
![Apple Podcast](https://img.shields.io/badge/Apple_Podcasts-9933cc?logo=applepodcasts&logoColor=fff)
![Overcast](https://img.shields.io/badge/Overcast-fc7e0f?logo=overcast&logoColor=fff)
![Pocket Casts](https://img.shields.io/badge/Pocket_Casts-f43e37?logo=pocketcasts&logoColor=fff)
![Google Podcasts](https://img.shields.io/badge/Google_Podcasts-4285f4?logo=googlepodcasts&logoColor=fff)
![Amazon Music](https://img.shields.io/badge/Amazon_Music-46c3d0?logo=amazonmusic&logoColor=fff)

```markdown
![RSS](https://img.shields.io/badge/RSS-ffa500?logo=rss&logoColor=fff)
![Spotify](https://img.shields.io/badge/Spotify-1db954?logo=spotify&logoColor=fff)
![Apple Podcast](https://img.shields.io/badge/Apple_Podcasts-9933cc?logo=applepodcasts&logoColor=fff)
![Overcast](https://img.shields.io/badge/Overcast-fc7e0f?logo=overcast&logoColor=fff)
![Pocket Casts](https://img.shields.io/badge/Pocket_Casts-f43e37?logo=pocketcasts&logoColor=fff)
![Google Podcasts](https://img.shields.io/badge/Google_Podcasts-4285f4?logo=googlepodcasts&logoColor=fff)
![Amazon Music](https://img.shields.io/badge/Amazon_Music-46c3d0?logo=amazonmusic&logoColor=fff)
```

### Flat-square style

![RSS](https://img.shields.io/badge/RSS-ffa500?logo=rss&logoColor=fff&style=flat-square)
![Spotify](https://img.shields.io/badge/Spotify-1db954?logo=spotify&logoColor=fff&style=flat-square)
![Apple Podcast](https://img.shields.io/badge/Apple_Podcasts-9933cc?logo=applepodcasts&logoColor=fff&style=flat-square)
![Overcast](https://img.shields.io/badge/Overcast-fc7e0f?logo=overcast&logoColor=fff&style=flat-square)
![Pocket Casts](https://img.shields.io/badge/Pocket_Casts-f43e37?logo=pocketcasts&logoColor=fff&style=flat-square)
![Google Podcasts](https://img.shields.io/badge/Google_Podcasts-4285f4?logo=googlepodcasts&logoColor=fff&style=flat-square)
![Amazon Music](https://img.shields.io/badge/Amazon_Music-46c3d0?logo=amazonmusic&logoColor=fff&style=flat-square)

```markdown
![RSS](https://img.shields.io/badge/RSS-ffa500?logo=rss&logoColor=fff&style=flat-square)
![Spotify](https://img.shields.io/badge/Spotify-1db954?logo=spotify&logoColor=fff&style=flat-square)
![Apple Podcast](https://img.shields.io/badge/Apple_Podcasts-9933cc?logo=applepodcasts&logoColor=fff&style=flat-square)
![Overcast](https://img.shields.io/badge/Overcast-fc7e0f?logo=overcast&logoColor=fff&style=flat-square)
![Pocket Casts](https://img.shields.io/badge/Pocket_Casts-f43e37?logo=pocketcasts&logoColor=fff&style=flat-square)
![Google Podcasts](https://img.shields.io/badge/Google_Podcasts-4285f4?logo=googlepodcasts&logoColor=fff&style=flat-square)
![Amazon Music](https://img.shields.io/badge/Amazon_Music-46c3d0?logo=amazonmusic&logoColor=fff&style=flat-square)
```

### For-the-badge style

![RSS](https://img.shields.io/badge/RSS-ffa500?logo=rss&logoColor=fff&style=for-the-badge)
![Spotify](https://img.shields.io/badge/Spotify-1db954?logo=spotify&logoColor=fff&style=for-the-badge)
![Apple Podcast](https://img.shields.io/badge/Apple_Podcasts-9933cc?logo=applepodcasts&logoColor=fff&style=for-the-badge)
![Overcast](https://img.shields.io/badge/Overcast-fc7e0f?logo=overcast&logoColor=fff&style=for-the-badge)
![Pocket Casts](https://img.shields.io/badge/Pocket_Casts-f43e37?logo=pocketcasts&logoColor=fff&style=for-the-badge)
![Google Podcasts](https://img.shields.io/badge/Google_Podcasts-4285f4?logo=googlepodcasts&logoColor=fff&style=for-the-badge)
![Amazon Music](https://img.shields.io/badge/Amazon_Music-46c3d0?logo=amazonmusic&logoColor=fff&style=for-the-badge)

```markdown
![RSS](https://img.shields.io/badge/RSS-ffa500?logo=rss&logoColor=fff&style=for-the-badge)
![Spotify](https://img.shields.io/badge/Spotify-1db954?logo=spotify&logoColor=fff&style=for-the-badge)
![Apple Podcast](https://img.shields.io/badge/Apple_Podcasts-9933cc?logo=applepodcasts&logoColor=fff&style=for-the-badge)
![Overcast](https://img.shields.io/badge/Overcast-fc7e0f?logo=overcast&logoColor=fff&style=for-the-badge)
![Pocket Casts](https://img.shields.io/badge/Pocket_Casts-f43e37?logo=pocketcasts&logoColor=fff&style=for-the-badge)
![Google Podcasts](https://img.shields.io/badge/Google_Podcasts-4285f4?logo=googlepodcasts&logoColor=fff&style=for-the-badge)
![Amazon Music](https://img.shields.io/badge/Amazon_Music-46c3d0?logo=amazonmusic&logoColor=fff&style=for-the-badge)
```

**Comment by stolinski** [comment]
Thanks for the suggestion but I think we'll keep our own style for these as they match our button styles.
