### ISSUE TITLE
Typing the `i` key in any input causes the global shortcut to fire

### ISSUE THREAD

**Issue by wesbos** [syntaxfm/website#1464]
Open the the search and type `hi i am in it` - every `i` toggles the gobal shortcut. 

need to ignore this event when the event target is a typeable input

**Comment by wesbos** [comment]
not sure how to do it with this svelte package, but if we can access the event, we need to check for this:

```ts
const ignoredTags = [`INPUT`, `TEXTAREA`, `SELECT`, `OPTION`, `BUTTON`];
if (ignoredTags.includes(e.target.tagName)) return;
```

**Comment by wesbos** [comment]
Looks like they have a feature for this -but its not working. https://github.com/vnphanquang/svelte-put/issues/264

**Comment by stolinski** [comment]
Yeah I've been finding some wonkyness with this hotkeys extension. Considering ripping out.

**Comment by vnphanquang** [comment]
Apologies for jumping in. Please check [my comment here](https://github.com/vnphanquang/svelte-put/issues/264#issuecomment-1867194697).


The [shortcut action](https://github.com/vnphanquang/svelte-put/blob/6a7f187b03b8327d1614fb8c419bd1b034e62907/packages/actions/shortcut/src/shortcut.js#L96-L165) is not that much code so I'm sure you can

**Comment by stolinski** [comment]
I had to pull the shortcuts out entirely. There was a lot of odd things going on.
