### ISSUE TITLE
Guest pages add "https://github.com/" before guests' URLs

### ISSUE THREAD

**Issue by jm-wilson** [syntaxfm/website#1471]
Website links on guest pages currently point to GitHub with the guest's URL value appended.  I believe this link should point directly to the guest's URL.

For example, the link on https://syntax.fm/guest/feross-aboukhadijeh points to https://github.com/https://feross.org/:
![image](https://github.com/syntaxfm/website/assets/16032665/ebf88226-60ec-4286-b0a9-4bae315728bc)

It looks like "https://github.com/" is hardcoded before the guest URL on [this line](https://github.com/syntaxfm/website/blob/cc699fff8548c9f09507d788261dd27de67c693a/src/lib/hosts/HostSocialLink.svelte#L25).  I think this can probably be removed outright, but any guest URLs that don't begin with a schema would become relative links.

**Comment by themisterholliday** [comment]
If i'm not mistaken, this should be fixed with https://github.com/syntaxfm/website/pull/1470
