### ISSUE TITLE
UI Enhancement : Add Padding to Left and Right of the search box

### ISSUE THREAD

**Issue by TartejBrothers** [syntaxfm/website#1472]
- There is no padding on the left and right of the search bar on the mobile view but it is there in the desktop view.
![image](https://github.com/syntaxfm/website/assets/112921727/b7412511-fc27-4970-9fcc-f3af392f99d0)
- Adding some inline padding should help with this.

**Comment by V-Mokhun** [comment]
As I see, there is padding on the left side, but if you write long enough search query, close button will overflow it.

![telegram-cloud-photo-size-2-5257952664195551968-y](https://github.com/syntaxfm/website/assets/78966165/8ad42c04-bb65-4211-b10c-a1a52bae0dcb)

I would be happy to do a pull request that fixes search-input's padding
