### ISSUE TITLE
Playback Issue on Syntax.fm Website

### ISSUE THREAD

**Issue by miryamfv** [syntaxfm/website#1481]
Upon completing an episode on the Syntax.fm website, where attempting to play another episode immediately results in playback failure. To resume listening, you must reload the page.

https://www.loom.com/share/b6c14af557774ddd8499c2a73e260be3

**Comment by stolinski** [comment]
On it. Thank you @miryamfv

**Comment by stolinski** [comment]
Fix is incoming. Basically the player state needed to reset after completion because of the state machine we were using. It wasn't loading the new ep because it saw the status as already loaded.
