### ISSUE TITLE
Clicking on Permalink in Overcast takes me to mp3 instead of show notes page

### ISSUE THREAD

**Issue by queuebit** [syntaxfm/website#15]
<https://overcast.fm/+JaI5l2tzo>

Click on `Permalink` and I go to audio, and I want to go to show notes and get them links, yo.

**Comment by wesbos** [comment]
Hmm - not sure how to solve this. Ill have to look into how libsyn works

**Comment by thewheat** [comment]
I believe you'd need to change the `link` value in [your RSS](https://feed.syntax.fm/rss)
![image](https://user-images.githubusercontent.com/892961/46905975-2621e180-cf2e-11e8-9948-2a46785ffceb.png)

Basing that off https://overcast.fm/+Ip012dEg where the Permalink link goes to `https://twit.tv/shows/this-week-in-law/episodes/438`. Looking at the  [TWIL RSS](http://feeds.twit.tv/twil.xml) you can see that `link` and `comments` links to the website (but your RSS doesn't have `comments` so it should be `link`)

![image](https://user-images.githubusercontent.com/892961/46905981-4baeeb00-cf2e-11e8-851a-3eff9c06d746.png)

Sources say that `link` can be URL to the item / page and the `enclosure` would be the important bit for the actual media download
- https://validator.w3.org/feed/docs/rss2.html
- http://www.rssboard.org/rss-2-0#hrelementsOfLtitemgt
- https://github.com/simplepie/simplepie-ng/wiki/Spec:-iTunes-Podcast-RSS#link

**Comment by queuebit** [comment]
Episode 44 <https://feed.syntax.fm/rss> link should be:

```
<link>https://syntax.fm/show/044/how-to-learn-new-things-quickly</link
```

instead of
```
<link><![CDATA[https://traffic.libsyn.com/secure/syntax/Syntax044.mp3]]></link>
```

**Comment by wesbos** [comment]
Yep! The new shorlinks are Perfect for this! 

@iChris can you start to populate this field when publishing a show?

<img width="311" alt="Screenshot 2023-10-23 at 10 02 47 AM" src="https://github.com/syntaxfm/website/assets/176013/ae8a088c-d91f-4396-ae74-b5ff3d03bbe3">
