### ISSUE TITLE
Incorrect timestamps for over an hour-long episodes

### ISSUE THREAD

**Issue by hudochenkov** [syntaxfm/website#1513]
If episode is over 1 hour, all timestamps after 1 hour are made like if it is 0 hour. Both visual timestamp is incorrect and link to the place in the episode.

https://syntax.fm/show/688/ex-npm-employee-making-a-new-package-manager-vlt-with-darcy-clarke

Last two timestamps are after 1 hour.

![CleanShot 2024-01-21 at 23 05 22](https://github.com/syntaxfm/website/assets/654597/5c02516d-459c-42cc-afae-0cd32a33b90f)

**Comment by wesbos** [comment]
thanks a ton! Just fixed this
