### ISSUE TITLE
<head> tag continuously updated on /about

### ISSUE THREAD

**Issue by jordanpurinton** [syntaxfm/website#1530]
Repro steps:

- Go here: https://syntax.fm/about
- Look at the `<head>` tag

Maybe this is intended for the ms counter but figured I'd bring it up.

**Comment by wesbos** [comment]
<img width="184" alt="Screenshot 2024-02-09 at 11 41 35 AM" src="https://github.com/syntaxfm/website/assets/176013/a21f5ed7-ebb5-4d67-a561-995f881b758c">

Weird - svelte is adding an empty style tag to the head every time the MS counter updates.

Not sure its an issue or not, but very bizarre..

**Comment by stolinski** [comment]
Yeah I took a look at this for a min very weird.

**Comment by jordanpurinton** [comment]
Weird!

**Comment by wesbos** [comment]
Im gonna close this as "probably fine"
