### ISSUE TITLE
Intro and outro monster truck theme

### ISSUE THREAD

**Issue by aidev13** [syntaxfm/website#1547]
I noticed for awhile there is no monster truck intro!? I just didn't know if you guys were aware of this.

I listen over the web on my iPhone.

**Comment by wesbos** [comment]
we killed it! It was funny for a bit, but we and most listeners got sick of it.

**Comment by aidev13** [comment]
Ahhhhh, ok. I liked it. Lol oh well!

**Comment by wesbos** [comment]
haha glad to hear it - we will have to get something else !
