### ISSUE TITLE
Episode #727's transcript truncated

### ISSUE THREAD

**Issue by yg-i** [syntaxfm/website#1555]
Transcript is cut off at around 10:35 here:

https://syntax.fm/show/727/how-to-code-opinionated-typescript-stack-tooling-choices-explained/transcript

**Comment by wesbos** [comment]
thanks - uncovered a different issue when I went to delete and re-gen it. Fixing now, will get it re-generated.

**Comment by wesbos** [comment]
https://syntax.fm/show/727/how-to-code-opinionated-typescript-stack-tooling-choices-explained/transcript fixed
