### ISSUE TITLE
Syntax error in rss feed

### ISSUE THREAD

**Issue by mzaharie** [syntaxfm/website#1575]
> LAST ERROR:
> This XML document is invalid, likely due to invalid characters. XML error: No memory at line 10713, column 7

Is it the fact that the xml is too big?

**Comment by mzaharie** [comment]
In a rss reader app

**Comment by wesbos** [comment]
Which app? Screenshots? Our RSS feed loads fine for me: feed.syntax.fm

**Comment by mzaharie** [comment]
Ok, feedly works just fine... I was playing with [Inoreader](https://www.inoreader.com/)
