### ISSUE TITLE
When changing theme, grit bg not reloading

### ISSUE THREAD

**Issue by stolinski** [syntaxfm/website#1584]
<img width="871" alt="Screenshot 2024-02-29 at 9 01 34 AM" src="https://github.com/syntaxfm/website/assets/669383/d45321dc-79ae-45c8-9aca-60f68f953f45">

Only works after refresh.

**Comment by wesbos** [comment]
Seem the variable bg-root isn't being set when switching, but it is on page reload. 

<img width="377" alt="Screenshot 2024-03-25 at 11 57 17 AM" src="https://github.com/syntaxfm/website/assets/176013/cfa0ac0a-5117-45e7-8a13-f7e2a442ba22">

**Comment by wesbos** [comment]
Fixed that - going to use this issue for the cookie-theme issue as well
