### ISSUE TITLE
Add CJ's Avatar or Fix Avatar Render Logic 

### ISSUE THREAD

**Issue by ericzorn93** [syntaxfm/website#1597]
After listening to the most recent episode, I decided to give the website another look. Great work guys on improving page performance and overall UX. It looks sweet! Just a heads up, unfortunately, as we know, Wes was not able to also host [this episode](https://syntax.fm/show/742/potluck-migrating-to-typescript-semver-explained-accurate-timers-and-countdowns), however, we now have CJ as well 🎉 . Due to this, I just noticed that the two thumbnails for the host and guest profiles were for Wes and Scott. I think that this may be a small bug. Keep up the great work Wes, Scott and CJ! I have been a long-time listener for every episode since the show was released. 

<img width="1506" alt="Screenshot 2024-03-13 at 10 05 47 PM" src="https://github.com/syntaxfm/website/assets/22532542/a4b311bf-b6a4-4d3c-84df-7ff67ce64ab1">
<img width="1672" alt="Screenshot 2024-03-13 at 10 06 22 PM" src="https://github.com/syntaxfm/website/assets/22532542/edc6c6d9-77f3-4217-be34-084b02efc64e">

**Comment by ericzorn93** [comment]
Yeah that totally works. I am not familiar with the code base or what was happening to generate those thumbnails for every podcast attendee, but I just wanted to file the ticket in case it was a complicated change.

**Comment by stolinski** [comment]
Completed in https://github.com/syntaxfm/website/pull/1724
