### ISSUE TITLE
Codeium misspelled in the intro text

### ISSUE THREAD

**Issue by lalov1** [syntaxfm/website#1599]
I noticed Codeium is misspelled in the description in the following two podcasts:
- https://syntax.fm/show/638/roundup-sick-ai-tools-for-developers
- https://syntax.fm/show/728/ai-superpowers-with-kevin-hou-and-codeium

I don't see a way to edit this in the show notes, so I don't know where it's coming from. 
- https://github.com/syntaxfm/website/blob/main/shows/638%20-%20Hasty.md
- https://github.com/syntaxfm/website/blob/main/shows/728%20-%20AI%20Superpowers%20with%20Kevin%20Hou%20and%20Codeium.md

<img width="1200" alt="Screenshot 2024-03-15 at 4 29 00 PM" src="https://github.com/syntaxfm/website/assets/7785251/b385fc9e-3cba-4b1d-86e2-fb0295f1ae1b">

**Comment by stolinski** [comment]
We need a way to edit this AI created text becuase I've noticed a few issues with names see Kevin Howe in this example.

**Comment by lalov1** [comment]
Oh! It's AI-created! That makes sense since I didn't see a way to edit it in the markdown file.

**Comment by stolinski** [comment]
Closing in favor of a more direct issue
https://github.com/syntaxfm/website/issues/new
