### ISSUE TITLE
SVG's not reacting to theme change

### ISSUE THREAD

**Issue by stolinski** [syntaxfm/website#1607]
When changing themes, most of the svgs that have a theme change that are loaded as bg images don't change until refresh. This looks broken usually. Any thoughts @wesbos

**Comment by wesbos** [comment]
taking a look - I remember this being an issue

**Comment by wesbos** [comment]
related? https://github.com/syntaxfm/website/issues/1584

**Comment by wesbos** [comment]
Not an issue apparently. something else is funky
