### ISSUE TITLE
Visual Bug on Hover over People on Episode Card

### ISSUE THREAD

**Issue by akpclarke** [syntaxfm/website#1639]
I noticed that with 4 people listed in an episode, hovering over the bottom edge of the list of people on the episode card from the site's home/landing page causes a visual bug where the cursor gets caught in a loop of going in and out of the relevant div. See the attached video.

https://github.com/syntaxfm/website/assets/128757124/8f8ba78a-8031-44cb-b0ca-1e5c6c2718df

**Comment by wesbos** [comment]
Fixed! <img width="493" alt="Screenshot 2024-04-08 at 10 09 47 AM" src="https://github.com/syntaxfm/website/assets/176013/55f8660f-936b-4ec2-aa05-9d81ccd19573">
