### ISSUE TITLE
Incorrect date on episode 609

### ISSUE THREAD

**Issue by msmps** [syntaxfm/website#1671]
## Description

As part of this pull request #1667 I noticed what might be an incorrect date on episode 609 as it doesn't align with the date published on Spotify (**May**). You can see this highlighted and demonstrated in the screenshot.

## Screenshot

![CleanShot 2024-04-30 at 22 01 19@2x](https://github.com/syntaxfm/website/assets/7691252/f027be30-b48d-4934-8756-3e6a74c1dacc)

**Comment by wesbos** [comment]
thanks! fixed https://github.com/syntaxfm/website/pull/1716
