### ISSUE TITLE
ShareWindow accessibility label is "Recent searches"

### ISSUE THREAD

**Issue by loicteixeira** [syntaxfm/website#1697]
Looking at your `ShareWindow` component shared (ah!) on episode 775, I noticed it has [`aria-labelledby="search-header"`](https://github.com/syntaxfm/website/blob/37233763170eb396d4571e803ecf4ddeb35559b7/src/lib/share/ShareWindow.svelte#L35) which doesn't seem to be related.

I imagine it might be correct in some context, but I reckon it isn't when you share an episode:
<img width="1269" alt="syntaxfm_sharemodal_labellyby" src="https://github.com/syntaxfm/website/assets/6834938/154319e4-d0ec-4571-b056-de454e818259">

Thanks for all the amazing podcasts 🌟

**Comment by stolinski** [comment]
Fixed here: https://github.com/syntaxfm/website/pull/1809/commits/96b9b09d37fb74ec97afa30dd421726df28e4816
