### ISSUE TITLE
Newsletter signup confirmation

### ISSUE THREAD

**Issue by JackedNerd** [syntaxfm/website#1701]
Just a minor issue I noticed. When signing up to the newsletter (https://syntax.fm/snackpack) using the central signup, the confirmation page is white text on a white background which was confusing for a second. (Mac / Edge)

(The site looks great overall and absolutely love your podcast!! I only stumbled onto it a month or two ago, and it's been a refreshing listen during the work day. /cheers)

![Screenshot 2024-05-30 at 1 53 01 PM](https://github.com/syntaxfm/website/assets/29149304/1c26574c-3fad-43bd-aad6-d849d004d2b5)

**Comment by wesbos** [comment]
looks like this was related a some CSS not being loaded on convert kits side, seems to be fixed now! thanks again
