### ISSUE TITLE
Podcast description is missing in RSS feed

### ISSUE THREAD

**Issue by hudochenkov** [syntaxfm/website#1791]
Episodes 810 and 811 don't have a description in the [RSS feed](https://feed.syntax.fm/). It is empty:

```xml
<description><![CDATA[]]></description>
```

**Comment by wesbos** [comment]
thanks a ton - getting our editor on it right now!

**Comment by wesbos** [comment]
fixed! thanks again for the heads up

**Comment by hudochenkov** [comment]
My pleasure!

Thank you for the awesome podcast!
