### ISSUE TITLE
Accessibility bugs

### ISSUE THREAD

**Issue by siddharaj-suryavanshi** [syntaxfm/website#1808]
I was just listening to the HTML fundamentals podcast (great podcast!!) & as I am an accessibility consultant, out of curiosity I just went ahead & did some testing on the page and found few bugs.

So I have created a report with all details I could possibly add. I hope you take a look at the report & review these bugs and resolve them to improve the accessibility of the page!! 

Link to the report: https://docs.google.com/spreadsheets/d/1_lhYJ_kTxCQhbkCYqEDOr3f7ShEyGncUXBV11eUICpk/edit?gid=0#gid=0

**Comment by wesbos** [comment]
Been chatting over 𝕏 DM - thanks a ton for this! Seems like some pretty easy fixed for the most part - Really appreciate it!

**Comment by wesbos** [comment]
Fixed! thanks again for this!
