### ISSUE TITLE
Allow for episode urls that only contain the number

### ISSUE THREAD

**Issue by aquacash5** [syntaxfm/website#1812]
I have an episode number that I want to see the show notes for, it would be nice if I could just use the episode number in the URL. (Ex. `https://syntax.fm/show/808`)

**Comment by wesbos** [comment]
Hey! Right now the syntax.fm/808 will redirect you - do you see a use where the `/show/###` would be useful as well?

**Comment by aquacash5** [comment]
I was listening to the podcast on my phone and I wanted to load up the episode on my computer without paging though the episode list.

I guess this isn't as useful since the slug for the show doesn't actually matter.

`https://syntax.fm/show/808/the-future-of-javascript-frameworks-building-auth-db-design-tips-and-more` and `https://syntax.fm/show/808/420-69` load the same episode page.

**Comment by aquacash5** [comment]
I think a more user friendly thing would be to be able to type the episode number into the search.

That was the first thing I tried. Typing `808` into the search.

**Comment by aquacash5** [comment]
Duplicate of #1668

**Comment by wesbos** [comment]
sweet yeah that a great idea - will add that
