### ISSUE TITLE
Show number covers description text

### ISSUE THREAD

**Issue by josh-stillman** [syntaxfm/website#1859]
See example here:
<img width="1342" alt="Screenshot 2024-10-14 at 11 51 57 AM" src="https://github.com/user-attachments/assets/446f9164-007c-47bf-838d-d7c08626bb8e">

You might want to try setting the show description `<p>` to `position: relative` like you have it on the show details page.  That would look like:

![Screenshot 2024-10-14 at 12 03 10 PM](https://github.com/user-attachments/assets/101cabe8-63f0-4673-99f7-c55a9aeaf7f9)

P.S. Thanks so much for all you guys do!!  Syntax is an amazing resource that I've learned a ton from over the years!

**Comment by josh-stillman** [comment]
This is on latest Chrome.

**Comment by wesbos** [comment]
I see it - thank you. I wonder if there was a chrome bug which caused us to "fix" it in the first place. Taking a look now

**Comment by wesbos** [comment]
relative fixed it! Thanks again for the help on this one! https://github.com/syntaxfm/website/pull/1860

**Comment by josh-stillman** [comment]
My pleasure! 🙌 🎉
