### ISSUE TITLE
[Idea] Show transcript

### ISSUE THREAD

**Issue by karbassi** [syntaxfm/website#543]
Hey @wesbos and @stolinski — **thoughts on adding a show transcript?** 

## Why
Lots of times I'm listening to the show while doing other activities (_housework, walking the dog, exercise, etc_) and when I hear something I want to remember, I either have to stop what I'm doing, jot down the timestamp, or just remember to come back to the show, which requires me to relisten to the whole show.

It would be amazing if I could <kbd>CMD/CTRL</kbd> + <kbd>F</kbd> the show transcript for words.

Outside of this, it would help SEO, help non-English speakers, and obviously accessibility for our deaf/hard of hearing friends.

## How or ideas
The last thing any of us want is more work, so why not use AI services. I'd suggest using Otter but only because I've had experience using them.

### Examples

- https://blog.otter.ai/podcasters/
- https://www.temi.com/
- https://sonix.ai/

## Resources

- https://bellocollective.com/the-podcasters-guide-to-transcribing-audio-2121f9e7992f

**Comment by wesbos** [comment]
Thanks! I'm gonna use this thread as an update as to whats going on with the transcripts. We were asked about it on twitter today and we are definitely working on it! Will be a huge benefit to the podcast.

I did spend a few days going down the auto transcribed route. I specifically used Google voice-to-text. It was okay, but not good enough. 

So - we're going down human generated transcripts. I use Rev.com for my own personal courses and it works great. 

The major thing lately has been that the turn around time has gotten better. It used to be  4-5 days, which was often too slow for our show. Now it looks to be ~5-20 hours for a show which is fast enough. 

So - thinking of ways to automate this. I'm going to dip into github actions to see if we can code something where when a new show is committed to the repo, it orders the transcripts, and then once it's done it will receive a webhook ping to download an commit the transcript.

**Comment by stolinski** [comment]
Will track in newer issue #958
