### ISSUE TITLE
[Idea] Show Chapters

### ISSUE THREAD

**Issue by karbassi** [syntaxfm/website#544]
This is a _nice-to-have_ and **not** a must. Since you already have timestamps in the description, it would be amazing if the audio file contained chapters.

## Tools
- https://overcast.fm/forecast (I thought @wesbos said he used this app)
- https://chaptersapp.com/

## Resources
- https://medium.com/podcast-101/podcast-chapters-explained-bed72832640c

**Comment by stolinski** [comment]
This will be in the new app.

**Comment by karbassi** [comment]
@stolinski, the audio file you put on your RSS already has chapters. Thanks for doing that a few months back!
