### ISSUE TITLE
Suggestion: More obvious external links in the shownotes 

### ISSUE THREAD

**Issue by fabianmossberg** [syntaxfm/website#809]
After listening to an episode, i often check the shownotes to check out the stuff that was talked about in the episode.

Today, all links are a gray color, regardless of if it's a sponsor, a link to a specific timestamp in the episode, the usual links to Wes and Scott's Twitter/Instagram, or external links to stuff mentioned in the episode.

It would be great if the external links would be easier to spot.

**Comment by stolinski** [comment]
Completed in 1886545
