### ISSUE TITLE
Tech Stack

### ISSUE THREAD

**Issue by stolinski** [syntaxfm/website#927]
Updating to list the current choices.

App Framework: SvelteKit
CSS: PostCSS + Preset Env
Database: Planetscale
Podcast Content: MD synched to host + local db
Testing: Vitest for server tests, Playwright for UI tests
CI/CD: Github Actions
Host: Vercel

**Comment by wesbos** [comment]
Other questions we have been chatting about.

Runtime?   Node, Deno, Cloudflare?

Hosting? Vercel, Cloudflare, Deno Deploy?

Some other things to think about:

1. We will need cron jobs
2. We need some sort of CDN
3. we will need longer-running functions. A transcript request can take ~30-60 seconds (can confirm). Some others will allow you to fire the request off and come back later to check on it
4. github will be the Filesystem for the show notes, so whatever we pick needs good support of that


We will do a show on this

**Comment by stolinski** [comment]
This seems to be fairly buttoned up now.
