### ISSUE TITLE
Merch Site

### ISSUE THREAD

**Issue by stolinski** [syntaxfm/website#939]
Here are my initial thoughts:

Feels like Shopify is really the way to go here. I'm not sure how much we step in and do things ourselves, or if we just keep this as a separate website on a sub domain.

My feeling is that just skinning Shopify is probably the direction we should be going.

**Comment by wesbos** [comment]
I think you are right, especially with all the complexities around inventory, shipping, pick+pack.

That said, we do want lots of custom features, like give away codes and possibly earned codes from things like Github/Bug Boundty etc..

I know @dcramer wants this to also be for Senty's merch as well - a full in house solution - so we should have a call soon to talk about what is needed.

**Comment by stolinski** [comment]
https://ghost.org/ is an option as well, one that is customizable. But I can safely say that I don't want to build a fully custom anything here.

**Comment by stolinski** [comment]
I've done some hunting and it seems like Shopify is the obvious answer.

https://store.supabase.com/
https://store.gatsbyjs.org/

are two nice simple ecom sites that both use shopify, and offer the features that we need. I think that Supabase shop would be a good template to work off of in terms of base ui for everything. I don't personally think we need to go "headless" like the Gatsby site is given Shopify's modern theming.

**Comment by dcramer** [comment]
Shopfiy only deals w/ hosting and maybe payments right? I'm more worried about the core logistics tbqh

**Comment by stolinski** [comment]
We have a couple of ways to go with the logistics piece. We could utilize Sendoso via https://sendoso.zendesk.com/hc/en-us/articles/10092146826139-How-to-Sync-Shopify-to-Sendoso
Where we would have to create all merch ahead of time, store and ship with Sendoso

or 

We could take an ondemand route and keep no inventory. The on demand stuff will probably be more expensive, but more flexible.

**Comment by wesbos** [comment]
Big vote against the on demand stuff, its the reason why most people's merch sucks - they are all just slapping a logo on the same shirt.

Integrating with an existing pick-n-pack is ideal. I'm not sure how expensive Sendoso is, but there are lots of other options we can look into as well. 

Shipbob is pretty popular. 

I also had a bunch of devs reach out when I did mine who offered to let their significant other just run it from their garage. We might be too large for that though

**Comment by dcramer** [comment]
> Big vote against the on demand stuff, its the reason why most people's merch sucks - they are all just slapping a logo on the same shirt.

100% - it seems like a small lift if we can order, vet, then repeat order direct to a warehouse

**Comment by ckj** [comment]
> seems like a small lift if we can order, vet, then repeat order direct to a warehouse

This is how things currently work on our end, fwiw. We we work with our preferred vendors, have them ship to the Sendoso warehouse, and Sendoso ships to the recipient according to our preferences. Some things like our new customer welcome kits get packed in custom boxes, etc.

According to @stolinski's link above it looks like it can be fully automated from Shopify. My vote would be to start with this approach as the new work would be mostly Shopify related... wiring up it up to Sendoso, figuring out credit distribution via discount codes or some other mechanism, and designing a branded theme.

**Comment by stolinski** [comment]
This project is being tracked off GH.
