### ISSUE TITLE
v2 Database

### ISSUE THREAD

**Issue by stolinski** [syntaxfm/website#946]
For our database, I think we'll want to use something sql based given how good orms are at abstracting the actual sql stuff.

I lean towards Planetscale + Prisma given how nice it was for the voucher site.

Cloudflare D1 seems like a good option, but when exploring more, it's 1. still in alpha, 2. doesn't work with Prisma. We could go with Drizzle, but it's been in Alpha for almost a year now, so I'm not sure that's a great idea even though I do kinda want to go all Cloudflare for this app.

**Comment by wesbos** [comment]
I think going straight up MySQL would be ideal, then we can dev locally without having to connect to some service. Planet scale for production.

Another option is going SQlite - maybe worth investigating. I know Kenneth Computer Dodds runs his entire site on it. I like that it's just a file on your system, and has some nice admin tools

**Comment by stolinski** [comment]
I'm not personally convinced that it needs to be fully local for dev, but it does seems like Planetscale is just MySQL 8, and many people seem to have a workflow simple enough where you are using a local mysql db for dev and only use Planetscale for prod. Planetscale even has a blog where they mention doing that themselves https://planetscale.com/blog/building-planetscale-with-planetscale
