### ISSUE TITLE
Source Of Truth

### ISSUE THREAD

**Issue by stolinski** [syntaxfm/website#955]
As we explore new hosts for the pod, it's going to be important to truly understand where each piece of data is living as the source of truth. Right now we have Libsyn and MD as duplicating the source of truth. 

I've done some reflection on this and I'm not sure that .md being THE source of truth for the new site is the right way to go. 

Specifically, having .md will make it hard to query by meta data. AKA, find me all episodes with a specific guest. 

The big question becomes how do we maintain one location for all information, how do we keep that in sync with the pod host (if it ends up being Transistor) and how do we connect that to the website in a meaningful way to query and explore off of.

**Comment by wesbos** [comment]
Keeping markdown as the source of truth is important. It makes it easy to update, and anyone can submit edits. 

I picture up ingesting the data into a database on startup or build. When something changes, it gets pushed tot he db, and to the podcast host
