### ISSUE TITLE
Transcripts

### ISSUE THREAD

**Issue by wesbos** [syntaxfm/website#958]
Been trying out a bunch of services - Deepgram seems to be the best so far.

**Comment by benvinegar** [comment]
Relates to #991

**Comment by stolinski** [comment]
Might be useful to output these into "CuePoints" format so that way we can integrate directly with Mux https://www.mux.com/blog/interactive-video-transcript and their new chapters functionality that's going to be added to media chrome.

**Comment by edm00se** [comment]
As someone who frequently tries to remember the context in which I recall something neat being mentioned, thank you!
