### ISSUE TITLE
Show note Ingest

### ISSUE THREAD

**Issue by wesbos** [syntaxfm/website#960]
A function, endpoint, webhook or startup script that will find new or updated show markdown files, parse them out and input all that data into the DB. 

Not sure if we should be saving the MD in the database, or HTML in the DB. Will let @stolinski figure that one out.

**Comment by wesbos** [comment]
We also need to decide if we stick with regular markdown, or go MDX. 

I would like nice syntax highlighting, and the remark vscode plugin does that with VS code extensions

**Comment by stolinski** [comment]
Yeah, very true. I wouldn't hate mdx but it does limit where we can push the markdown later. There is an issue though that typically if you are putting md in the database, it doesn't play super nice with mdx, or at least when we tried to do it for LUT we had to stick with straight md unless what we are storing in the db is compiled html/css.

**Comment by stolinski** [comment]
Although, here is another idea. Store the link to the mdx file with the meta data in the db and not the html or the md itself.

**Comment by stolinski** [comment]
All shows correctly importing. Going to tune up the db schema and tighten up code before pushing.

**Comment by stolinski** [comment]
Show notes now import via admin ui or via webhook. All import process check file hash to make sure file is modified if it exists.
