### ISSUE TITLE
Routing URLS

### ISSUE THREAD

**Issue by wesbos** [syntaxfm/website#968]
@stolinski thought I'd mention this before you get too deep into the routing.

There are a few things:

1. We need to maintain the existing url structure of `https://syntax.fm/show/100/slug` 

The slug doesn't actually look up anything, and is just for SEO, but we should keep those the same

2. I'd love to add shortlinks for `syntax.fm/543` so we can easily call out shows - so a middleware/hook in sveltekit would work here?

**Comment by stolinski** [comment]
1. No prob. Will do.
2. There is a neat feature in SK called params matching where you can provide a route parameter a regex match. Should be a bit easier than using hooks for this. Will give it a go.

**Comment by stolinski** [comment]
<img width="493" alt="Screenshot 2023-05-16 at 11 46 51 AM" src="https://github.com/syntaxfm/website/assets/669383/11a2d2a9-fcb9-4e7b-af04-b557e85bfeb8">
<img width="480" alt="Screenshot 2023-05-16 at 11 46 42 AM" src="https://github.com/syntaxfm/website/assets/669383/96c26bea-c62e-461a-949e-de7733454275">

Bingo. Now will just do a quick db call and throw a redirect.
The route name is [number=show_number] which auto matches to a param matcher named show_number

**Comment by wesbos** [comment]
👌
